# pets models
from django.db import models
from django.utils.text import slugify

'''
The fields Name and Pet Photo are required:
•	Name - it should consist of a maximum of 30 characters.
•	Personal Pet Photo - the user can link a picture using a URL
The field date of birth is optional:
•	Date of Birth - pet's day, month, and year of birth

There should be created one more field that will be auto-populated with the following information:
•	Slug - a slug automatically generated using the pet's name and t
The slug is part of the URL and as you know each URL should be unique: 
'''


class Pet(models.Model):
    MAX_NAME = 30  # more advanced way
    name = models.CharField(
        max_length=MAX_NAME,
    )
    # linking a picture
    personal_photo = models.URLField()

    # defining optional parameters
    date_of_birth = models.DateField(
        null=True,
        blank=True,
        editable=False,
    )

    # Slug:
    # should - null and blank = False
    # unique - unique=True
    slug = models.SlugField(
        unique=True,
        blank=True,
        null=True,
    )

    # Autogenerated slug - overriding save()
    def save(self, *args, **kwargs):
        # Create/Update - in order to use the ID when slug is not provided
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f"{self.id}-{self.name}")
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} with ID = {self.id}"

