# Generated by Django 4.1.1 on 2022-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_slug'),
        ('photos', '0002_rename_photo_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
