# Generated by Django 4.1.1 on 2022-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photos_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
