# Generated by Django 4.1.1 on 2022-10-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_slug'),
        ('common', '0001_initial'),
        ('photos', '0005_alter_photos_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
